<?php

namespace App\Actions\Accounting;

use App\Models\Accounting\Journal;
use Illuminate\Support\Facades\DB;
use RuntimeException;

/**
 * Voids a posted journal by posting an equal-and-opposite REVERSING journal
 * rather than editing or deleting it (Section 20 Financial Immutability is
 * never broken — the original entries stay in the ledger forever, and the
 * reversal's opposite entries net them to zero automatically in every
 * balance/report query, with no special "exclude voided" filtering needed
 * anywhere).
 */
class VoidJournal
{
    public function __construct(private PostJournal $postJournal) {}

    public function handle(Journal $journal, ?int $userId): Journal
    {
        if (! $journal->canBeVoided()) {
            throw new RuntimeException(
                $journal->source_type !== null
                    ? 'This journal was generated by another document and must be voided through that document instead.'
                    : 'This journal has already been voided or is itself a reversal.'
            );
        }

        $journal->loadMissing('entries');

        return DB::transaction(function () use ($journal, $userId) {
            $reversal = $this->postJournal->handle([
                'date' => now()->toDateString(),
                'reference' => $journal->reference ? "Reversal of {$journal->reference}" : "Reversal of Journal #{$journal->id}",
                'description' => "Reversal of Journal #{$journal->id}".($journal->description ? " ({$journal->description})" : ''),
                'created_by' => $userId,
                'lines' => $journal->entries->map(fn ($entry) => [
                    'account_id' => $entry->account_id,
                    'customer_id' => $entry->customer_id,
                    'vendor_id' => $entry->vendor_id,
                    'debit' => (string) $entry->credit,
                    'credit' => (string) $entry->debit,
                    'description' => $entry->description,
                ])->all(),
            ]);

            $reversal->update(['reversal_of_journal_id' => $journal->id]);
            $journal->update(['voided_at' => now()]);

            return $journal->fresh(['entries', 'reversalJournal']);
        });
    }
}
